/*
* This is the C# struct converted from model_config.json.
* The original JSON file is licensed under Apache 2.0 by Google LLC, and can be obtained from the following link.
* https://github.com/google/magika/blob/v0.5.0/python/magika/models/standard_v1/model_config.json
*/

namespace magika;

public readonly record struct ModelConfig
{
    public string[] target_labels_space {get; init;}
    public string dataset_format {get; init;}

    public Dictionary<string, int> input_sizes { get; init; }
    public Dictionary<string, float> thresholds { get; init; }
    public Dictionary<string, string> model_output_overwrite_map { get; init; }

    public ModelConfig()
    {
        this.input_sizes = new Dictionary<string, int>(){
            {"beg", 512},
            {"mid", 512},
            {"end", 512}
        };
        this.dataset_format = "int-concat/one-hot";
        this.target_labels_space = [
            "ai",
            "apk",
            "appleplist",
            "asm",
            "asp",
            "batch",
            "bmp",
            "bzip",
            "c",
            "cab",
            "cat",
            "chm",
            "coff",
            "crx",
            "cs",
            "css",
            "csv",
            "deb",
            "dex",
            "dmg",
            "doc",
            "docx",
            "elf",
            "emf",
            "eml",
            "epub",
            "flac",
            "gif",
            "go",
            "gzip",
            "hlp",
            "html",
            "ico",
            "ini",
            "internetshortcut",
            "iso",
            "jar",
            "java",
            "javabytecode",
            "javascript",
            "jpeg",
            "json",
            "latex",
            "lisp",
            "lnk",
            "m3u",
            "macho",
            "makefile",
            "markdown",
            "mht",
            "mp3",
            "mp4",
            "mscompress",
            "msi",
            "mum",
            "odex",
            "odp",
            "ods",
            "odt",
            "ogg",
            "outlook",
            "pcap",
            "pdf",
            "pebin",
            "pem",
            "perl",
            "php",
            "png",
            "postscript",
            "powershell",
            "ppt",
            "pptx",
            "python",
            "pythonbytecode",
            "rar",
            "rdf",
            "rpm",
            "rst",
            "rtf",
            "ruby",
            "rust",
            "scala",
            "sevenzip",
            "shell",
            "smali",
            "sql",
            "squashfs",
            "svg",
            "swf",
            "symlinktext",
            "tar",
            "tga",
            "tiff",
            "torrent",
            "ttf",
            "txt",
            "unknown",
            "vba",
            "wav",
            "webm",
            "webp",
            "winregistry",
            "wmf",
            "xar",
            "xls",
            "xlsb",
            "xlsx",
            "xml",
            "xpi",
            "xz",
            "yaml",
            "zip",
            "zlibstream"
        ];

        this.thresholds = new Dictionary<string, float>(){
            {"ai", 0.95f},
            {"apk", 0.5f},
            {"appleplist", 0.95f},
            {"asm", 0.85f},
            {"asp", 0.5f},
            {"batch", 0.65f},
            {"bmp", 0.95f},
            {"bzip", 0.95f},
            {"c", 0.7f},
            {"cab", 0.95f},
            {"cat", 0.95f},
            {"chm", 0.95f},
            {"coff", 0.95f},
            {"crx", 0.95f},
            {"cs", 0.95f},
            {"css", 0.5f},
            {"csv", 0.5f},
            {"deb", 0.95f},
            {"dex", 0.95f},
            {"dmg", 0.95f},
            {"doc", 0.5f},
            {"docx", 0.91f},
            {"elf", 0.95f},
            {"emf", 0.95f},
            {"eml", 0.95f},
            {"epub", 0.95f},
            {"flac", 0.95f},
            {"gif", 0.95f},
            {"go", 0.95f},
            {"gzip", 0.95f},
            {"hlp", 0.95f},
            {"html", 0.75f},
            {"ico", 0.95f},
            {"ini", 0.55f},
            {"internetshortcut", 0.95f},
            {"iso", 0.95f},
            {"jar", 0.55f},
            {"java", 0.91f},
            {"javabytecode", 0.95f},
            {"javascript", 0.8f},
            {"jpeg", 0.95f},
            {"json", 0.75f},
            {"latex", 0.5f},
            {"lisp", 0.95f},
            {"lnk", 0.95f},
            {"m3u", 0.95f},
            {"macho", 0.95f},
            {"makefile", 0.95f},
            {"markdown", 0.9f},
            {"mht", 0.95f},
            {"mp3", 0.95f},
            {"mp4", 0.95f},
            {"mscompress", 0.95f},
            {"msi", 0.7f},
            {"mum", 0.95f},
            {"odex", 0.95f},
            {"odp", 0.95f},
            {"ods", 0.95f},
            {"odt", 0.95f},
            {"ogg", 0.95f},
            {"outlook", 0.95f},
            {"pcap", 0.95f},
            {"pdf", 0.95f},
            {"pebin", 0.95f},
            {"pem", 0.95f},
            {"perl", 0.85f},
            {"php", 0.5f},
            {"png", 0.95f},
            {"postscript", 0.95f},
            {"powershell", 0.95f},
            {"ppt", 0.7f},
            {"pptx", 0.85f},
            {"python", 0.85f},
            {"pythonbytecode", 0.95f},
            {"rar", 0.95f},
            {"rdf", 0.95f},
            {"rpm", 0.95f},
            {"rst", 0.95f},
            {"rtf", 0.95f},
            {"ruby", 0.93f},
            {"rust", 0.95f},
            {"scala", 0.95f},
            {"sevenzip", 0.95f},
            {"shell", 0.85f},
            {"smali", 0.95f},
            {"sql", 0.7f},
            {"squashfs", 0.95f},
            {"svg", 0.95f},
            {"swf", 0.95f},
            {"symlinktext", 0.95f},
            {"tar", 0.95f},
            {"tga", 0.95f},
            {"tiff", 0.95f},
            {"torrent", 0.95f},
            {"ttf", 0.95f},
            {"txt", 0.94f},
            {"unknown", 0.95f},
            {"vba", 0.5f},
            {"wav", 0.95f},
            {"webm", 0.95f},
            {"webp", 0.95f},
            {"winregistry", 0.95f},
            {"wmf", 0.95f},
            {"xar", 0.95f},
            {"xls", 0.75f},
            {"xlsb", 0.5f},
            {"xlsx", 0.95f},
            {"xml", 0.7f},
            {"xpi", 0.93f},
            {"xz", 0.95f},
            {"yaml", 0.7f},
            {"zip", 0.95f},
            {"zlibstream", 0.95f}
        };

        this.model_output_overwrite_map = new Dictionary<string, string>(){
            {"odex", "elf"}
        };
    }
}
